apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tcp-route-sync: '34569'
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
    tier: mysql
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
      - image: frodenas/mysql:5.6
        name: mysql
        env:
        - name: MYSQL_USERNAME
          value: admin
        - name: MYSQL_PASSWORD
          value: mypassword
        - name: MYSQL_DBNAME
          value: mydb
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /data
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
